# Generated by Django 4.1.4 on 2022-12-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0004_alter_chat_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="fav_movie",
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
